# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4fcb1384eaac200dba9acbce2d2ac3d09cbdcbb767339cd1fe28be685ba71f5a737275f101d2e2d58b14266940cf0dc8bc35f69c21e248544bd07db4a2761e5

test:
  secret_key_base: 059f6404cdbd04afd9a3fbd845b602c1a89455b227273661dbfb891402c96c151e8305578bbf031683566102e71b4a4752e49733df779f14078617ecdbb2ed21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
